spring:
  flyway:
    enabled: false
  application:
    name: dipalza
  profiles:
    active: dev-sec
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.sql.init.SqlInitializationAutoConfiguration

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8080
  tomcat:
    relaxed-query-chars: '|,{,},[,],^,`,<,>,",%'
# logging común
logging:
  level:
    root: INFO
    org.springframework.security: INFO

