spring:
  flyway:
    enabled: false
  application:
    name: dipalza
  profiles:
    active: dev-sec   # cambia aquí por defecto si quieres

server:
  port: 8080
  tomcat:
    relaxed-query-chars: '|,{,},[,],^,`,<,>,",%'
# logging común
logging:
  level:
    root: INFO
    org.springframework.security: INFO

